config/routes.rb
Rails.application.routes.draw do
  get  "kifus/new/:rid" => "kifus#new"

  resources :rooms

  resources :kifus

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :kifus
end

app/controllers/rooms_controller.rb
require 'securerandom'

class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :auth, only: [:show, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @sgfdata = ""
    if not session[:sgfdata].blank?
      @sgfdata = session[:sgfdata]
      session[:sgfdata] = nil
    end
    @error_message = params[:error_message]
    @kifus = @room.kifus.sort_by { |kifu| kifu.created_at.to_i }
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.key = SecureRandom.urlsafe_base64(64)

    respond_to do |format|
      if @room.save
        format.html { redirect_to view_context.sec_room_path(@room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to view_context.sec_room_path(@room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to view_context.sec_room_path(@room), notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :key)
    end

    def auth
      key = params[:rtok]
      raise "Access Denied" unless key && @room.key.length == key.length && @room.key == key
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def sec_room_path(room)
    rooms_path + "/#{room.id}?#{URI.encode_www_form(rtok: room.key)}"
  end
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.hidden_field :key %>
  <%= hidden_field_tag :rtok, @room.key %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Back', sec_room_path(@room) %>

app/views/rooms/index.html.erb
<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<style>

table {
  width: auto;
  border-spacing: 0;
  font-size: 14pt;
}

table th {
  color: #fff;
  padding: 8px 15px;
  background: #258;
  background:-moz-linear-gradient(rgba(34,85,136,0.7), rgba(34,85,136,0.9) 50%);
  background:-webkit-gradient(linear, 100% 0%, 100% 50%, from(rgba(34,85,136,0.7)), to(rgba(34,85,136,0.9)));
  font-weight: bold;
  border-left:1px solid #258;
  border-top:1px solid #258;
  border-bottom:1px solid #258;
  line-height: 120%;
  text-align: center;
  text-shadow:0 -1px 0 rgba(34,85,136,0.9);
  box-shadow: 0px 1px 1px rgba(255,255,255,0.3) inset;
}

table th:last-child {
  border-radius:0 5px 0 0;
  border-right:1px solid #aaa;
}

table tr td {
  padding: 8px 15px;
  border-bottom: 1px solid #84b2e0;
  border-left: 1px solid #84b2e0;
  text-align: left;
}

table tr td:last-child {
  border-right: 1px solid #aaa;
}

table tr {
  background: #fff;
}

table tr:nth-child(2n+1) {
  background: #f1f6fc;
}


</style>



<h1><%= link_to @room.name, edit_room_path(@room) %></h1>

<br />
<br />
<%= link_to '新規', sec_new_kifu_path(@room) %>
<table>
  <thead>
    <tr>
      <th width=100px>対局日</th>
      <th></th>
      <th width=90px>作成日</th>
      <th width=90px>更新日</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @kifus.each do |kifu| %>
      <% facade = kifu.sgf_node_facade %>
      <tr>
        <td><%= ((d = kifu.play_date) && d.strftime("%Y/%m/%d")) || (facade && facade.date) %></td>
        <td><%= facade && facade.title  %></td>
        <td><%= kifu.created_at.strftime("%Y/%m/%d") %></td>
        <td><%= kifu.updated_at.strftime("%Y/%m/%d") %></td>
        <td><%= link_to '表示', sec_kifu_path(kifu) %></td>
        <td><%= link_to '削除', sec_kifu_path(kifu), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<br />
<br />
<%= form_tag({controller: :kifus, action: :create, method: "post" }, {multipart: true}) do %>
Sgf アップロード(ファイル):<br />
<%= file_field_tag 'sgffile' %>
<%= hidden_field_tag :rid,  @room.id  %>
<%= hidden_field_tag :rtok, @room.key %>
<%= submit_tag "Upload" %>
<% end %>

<br />
<% if @error_message %>
<p style="color: red;"><%= @error_message %></p>
<% end %>
<%= form_tag({controller: :kifus, action: :create, method: "post" }) do %>
Sgf アップロード(生データ):<br />
<%= text_area_tag 'sgfdata', @sgfdata, size: "50x10" %>
<%= hidden_field_tag :rid,  @room.id  %>
<%= hidden_field_tag :rtok, @room.key %>
<%= submit_tag "Upload" %>
<br />
<% end %>